import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [ { title: "Entrar — Ki Sapato" }, { name: "description", content: "Acesse sua conta Ki Sapato ou crie seu cadastro." }, { property: "og:title", content: "Minha conta — Ki Sapato" }, { property: "og:description", content: "Entre para acessar sua conta." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" } ] }), component: AuthPage });
function AuthPage() {
  const navigate=useNavigate(); const [mode,setMode]=useState<"login"|"signup">("login"); const [loading,setLoading]=useState(false); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState("");
  useEffect(()=>{ supabase.auth.getUser().then(({data})=>{ if(data.user) navigate({to:"/conta"}); }); },[navigate]);
  async function submit(e:React.FormEvent){ e.preventDefault(); setLoading(true); if(mode==="signup"){ const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin, data:{full_name:name}}}); if(error) toast.error(error.message); else toast.success("Confira seu e-mail para confirmar o cadastro."); } else { const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) toast.error("E-mail ou senha inválidos."); else navigate({to:"/conta"}); } setLoading(false); }
  async function google(){ const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin}); if(result.error) toast.error("Não foi possível entrar com Google."); else if(!result.redirected) navigate({to:"/conta"}); }
  return <div className="mx-auto grid max-w-[1100px] px-4 py-16 lg:grid-cols-2 lg:px-8"><div className="hidden bg-foreground p-12 text-background lg:flex lg:flex-col lg:justify-end"><p className="text-xs uppercase tracking-[0.18em] text-background/60">Bem-vindo à Ki Sapato</p><p className="mt-3 font-display text-5xl leading-none">Seu estilo, suas escolhas, em um só lugar.</p></div><div className="border p-7 sm:p-12"><h1 className="font-display text-4xl">{mode==="login"?"Entre na sua conta":"Crie sua conta"}</h1><p className="mt-2 text-sm text-muted-foreground">{mode==="login"?"Acompanhe suas escolhas e acesse a área administrativa.":"Cadastre-se para uma experiência mais prática."}</p><Button variant="outline" onClick={google} className="mt-8 h-12 w-full rounded-none">Continuar com Google</Button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>ou use seu e-mail<span className="h-px flex-1 bg-border"/></div><form onSubmit={submit} className="space-y-5">{mode==="signup"&&<div><Label htmlFor="name">Nome completo</Label><Input id="name" value={name} onChange={e=>setName(e.target.value)} required className="mt-2 h-12 rounded-none"/></div>}<div><Label htmlFor="email">E-mail</Label><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="mt-2 h-12 rounded-none"/></div><div><div className="flex justify-between"><Label htmlFor="password">Senha</Label>{mode==="login"&&<button type="button" onClick={async()=>{if(!email)return toast.error("Informe seu e-mail primeiro.");await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});toast.success("Enviamos as instruções por e-mail.");}} className="text-xs underline">Esqueci minha senha</button>}</div><Input id="password" type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required className="mt-2 h-12 rounded-none"/></div><Button disabled={loading} className="h-12 w-full rounded-none">{loading&&<Loader2 className="animate-spin"/>}{mode==="login"?"Entrar":"Criar conta"}</Button></form><button type="button" className="mt-6 w-full text-center text-sm underline" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Ainda não tenho conta":"Já tenho uma conta"}</button></div></div>;
}