import { createFileRoute, Link } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCart } from "@/lib/cart";
import { formatPrice } from "@/lib/catalog";

export const Route = createFileRoute("/checkout")({ head: () => ({ meta: [ { title: "Finalizar compra — Ki Sapato" }, { name: "description", content: "Checkout demonstrativo da Ki Sapato." }, { property: "og:title", content: "Finalizar compra — Ki Sapato" }, { property: "og:description", content: "Escolha entrega e pagamento." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" } ] }), component: CheckoutPage });
function CheckoutPage() {
  const cart = useCart(); const [step,setStep] = useState(1); const shipping = cart.total >= 399 || step < 3 ? 0 : 24.9;
  if (step === 4) return <div className="mx-auto max-w-xl px-6 py-24 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-foreground text-background"><Check className="size-7"/></div><h1 className="mt-6 font-display text-5xl">Pedido demonstrativo concluído</h1><p className="mt-4 text-muted-foreground">Nenhuma cobrança foi realizada. Entre em contato pelo WhatsApp para confirmar disponibilidade.</p><Button asChild className="mt-8 rounded-none"><a href="https://wa.me/5551998113318" target="_blank" rel="noreferrer">Falar com a loja</a></Button></div>;
  return <div className="mx-auto max-w-[1100px] px-4 py-12 lg:px-8"><h1 className="font-display text-5xl">Finalizar compra</h1><div className="mt-8 grid grid-cols-4 border-y py-4 text-center text-[10px] uppercase tracking-[0.1em]">{["Contato","Entrega","Pagamento","Confirmação"].map((label,i)=><span key={label} className={step>=i+1?"font-semibold text-foreground":"text-muted-foreground"}>{i+1}. {label}</span>)}</div><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_340px]"><section>{step===1&&<FormSection title="Seus dados"><Field label="Nome completo"/><Field label="E-mail" type="email"/><Field label="WhatsApp"/></FormSection>}{step===2&&<FormSection title="Como deseja receber?"><label className="flex cursor-pointer items-center justify-between border p-5"><span><strong>Retirada na loja</strong><small className="mt-1 block text-muted-foreground">Pátio Urbano — grátis</small></span><input type="radio" name="shipping" defaultChecked/></label><label className="mt-3 flex cursor-pointer items-center justify-between border p-5"><span><strong>Entrega padrão</strong><small className="mt-1 block text-muted-foreground">Prazo estimado após confirmação</small></span><span>R$ 24,90</span></label></FormSection>}{step===3&&<FormSection title="Pagamento"><label className="flex cursor-pointer items-center justify-between border p-5"><span><strong>Pix</strong><small className="mt-1 block text-muted-foreground">Confirmação com a loja</small></span><input type="radio" name="pay" defaultChecked/></label><label className="mt-3 flex cursor-pointer items-center justify-between border p-5"><span><strong>Cartão</strong><small className="mt-1 block text-muted-foreground">Parcelamento conforme o valor</small></span><input type="radio" name="pay"/></label></FormSection>}<div className="mt-8 flex justify-between"><Button variant="outline" className="rounded-none" disabled={step===1} onClick={()=>setStep(step-1)}>Voltar</Button><Button className="rounded-none" onClick={()=>setStep(step+1)}>{step===3?"Confirmar demonstração":"Continuar"}</Button></div></section><aside className="border p-6"><h2 className="font-display text-2xl">Resumo do pedido</h2><div className="mt-5 space-y-3 text-sm">{cart.items.map((i)=><div key={i.product.slug} className="flex justify-between gap-4"><span>{i.quantity}× {i.product.name}</span><span>{formatPrice(i.quantity*i.product.price)}</span></div>)}</div><div className="mt-5 flex justify-between border-t pt-5"><span>Total</span><strong>{formatPrice(cart.total+shipping)}</strong></div></aside></div></div>;
}
function FormSection({ title,children }: { title:string; children:React.ReactNode }) { return <div className="space-y-5"><h2 className="font-display text-3xl">{title}</h2>{children}</div>; }
function Field({ label,type="text" }: { label:string; type?:string }) { const id=label.toLowerCase().replaceAll(" ","-"); return <div><Label htmlFor={id}>{label}</Label><Input id={id} type={type} className="mt-2 h-12 rounded-none"/></div>; }