import { createFileRoute, Link } from "@tanstack/react-router";
import { Minus, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart";
import { formatPrice, productImage } from "@/lib/catalog";

export const Route = createFileRoute("/sacola")({ head: () => ({ meta: [ { title: "Sacola — Ki Sapato" }, { name: "description", content: "Revise os itens da sua sacola Ki Sapato." }, { property: "og:title", content: "Sacola — Ki Sapato" }, { property: "og:description", content: "Revise sua seleção antes de finalizar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" } ] }), component: CartPage });
function CartPage() {
  const cart = useCart();
  if (!cart.items.length) return <div className="mx-auto max-w-2xl px-6 py-24 text-center"><h1 className="font-display text-5xl">Sua sacola está vazia</h1><p className="mt-3 text-muted-foreground">Descubra novidades para todos os estilos.</p><Button asChild className="mt-8 h-12 rounded-none"><Link to="/produtos" search={{}}>Ir às compras</Link></Button></div>;
  return <div className="mx-auto max-w-[1200px] px-4 py-12 lg:px-8"><h1 className="font-display text-5xl">Sua sacola</h1><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_360px]"><div className="divide-y border-y">{cart.items.map((item) => <article key={`${item.product.slug}-${item.size}-${item.color}`} className="grid grid-cols-[110px_1fr] gap-5 py-6 sm:grid-cols-[150px_1fr_auto]"><img src={productImage(item.product)} alt={item.product.name} width={1024} height={1024} className="aspect-square w-full object-cover"/><div><h2 className="font-display text-2xl">{item.product.name}</h2><p className="mt-2 text-xs text-muted-foreground">Cor: {item.color} · Tamanho: {item.size}</p><p className="mt-3 font-semibold">{formatPrice(item.product.price)}</p><div className="mt-5 inline-flex items-center border"><Button variant="ghost" size="icon" className="rounded-none" onClick={() => cart.updateQuantity(item.product.slug,item.quantity-1)}><Minus/></Button><span className="w-9 text-center text-sm">{item.quantity}</span><Button variant="ghost" size="icon" className="rounded-none" onClick={() => cart.updateQuantity(item.product.slug,item.quantity+1)}><Plus/></Button></div></div><Button variant="ghost" size="icon" className="rounded-none" aria-label="Remover item" onClick={() => cart.removeItem(item.product.slug)}><Trash2/></Button></article>)}</div><aside className="h-fit border p-6"><h2 className="font-display text-3xl">Resumo</h2><div className="mt-6 flex justify-between text-sm"><span>Subtotal</span><strong>{formatPrice(cart.total)}</strong></div><div className="mt-3 flex justify-between text-sm"><span>Entrega</span><span>Calculada no checkout</span></div>{cart.total < 399 && <p className="mt-5 border-t pt-4 text-xs text-muted-foreground">Faltam {formatPrice(399-cart.total)} para o frete grátis.</p>}<div className="mt-5 flex justify-between border-t pt-5 text-lg"><span>Total</span><strong>{formatPrice(cart.total)}</strong></div><Button asChild className="mt-6 h-13 w-full rounded-none uppercase tracking-[0.12em]"><Link to="/checkout">Finalizar compra</Link></Button><p className="mt-4 text-center text-xs text-muted-foreground">Ambiente demonstrativo — nenhum pagamento será cobrado.</p></aside></div></div>;
}